# syntax=docker/dockerfile:1
# Requires BuildKit (default in Docker 23+) for cache mounts.

# --- Stage 1: install dependencies with Bun ---
FROM oven/bun:1-alpine AS deps
WORKDIR /app

# Copy lockfile and manifest only — this layer is cached until they change
COPY package.json bun.lock ./

# Persistent Bun cache across builds → near-instant reinstalls
RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

# --- Stage 2: build the Next.js app ---
FROM oven/bun:1-alpine AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* vars are inlined at build time — inject real values via --build-arg
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

ARG NEXT_PUBLIC_ADMIN_API_URL
ENV NEXT_PUBLIC_ADMIN_API_URL=${NEXT_PUBLIC_ADMIN_API_URL}

ARG NEXT_PUBLIC_POCKETBASE_URL
ENV NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL}

# Server-side vars: needed at build only so static prerendering doesn't crash.
# Real values are injected at runtime by the orchestrator.
ARG POCKETBASE_URL=https://pb.dvcklab.work
ENV POCKETBASE_URL=${POCKETBASE_URL}

ARG POCKETBASE_ADMIN_EMAIL=build@placeholder.local
ENV POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}

ARG POCKETBASE_ADMIN_PASSWORD=placeholder
ENV POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}

ARG DATABASE_URL=mysql://build:build@localhost:3306/build
ENV DATABASE_URL=${DATABASE_URL}

ARG BETTER_AUTH_SECRET=build-time-placeholder-secret-not-used-at-runtime
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

ARG BETTER_AUTH_URL=http://localhost:3000
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}

# Persistent Next.js webpack cache across builds → much faster rebuilds
RUN --mount=type=cache,target=/app/.next/cache \
    bun run build

# --- Stage 3: minimal runtime image ---
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# ca-certificates for HTTPS outbound calls; libc6-compat for any glibc-linked bits
RUN apk add --no-cache ca-certificates libc6-compat

# Copy standalone output generated by Next.js (node_modules is traced/minimal)
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static
COPY --from=builder --chown=node:node /app/public ./public

USER node

EXPOSE 3000

CMD ["node", "server.js"]
