# syntax=docker/dockerfile:1

# --- Stage 1: install dependencies with Bun ---
FROM oven/bun:1-slim AS deps
WORKDIR /app

# Copy lockfile and manifest
COPY package.json bun.lock ./

# Install production + build dependencies
RUN bun install --frozen-lockfile

# --- Stage 2: build the Next.js app ---
FROM oven/bun:1-slim AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Copy installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build arguments for any NEXT_PUBLIC_* vars Dokploy injects at build time
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

ARG NEXT_PUBLIC_ADMIN_API_URL
ENV NEXT_PUBLIC_ADMIN_API_URL=${NEXT_PUBLIC_ADMIN_API_URL}

ARG NEXT_PUBLIC_POCKETBASE_URL
ENV NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL}

ARG POCKETBASE_URL
ENV POCKETBASE_URL=${POCKETBASE_URL}

ARG POCKETBASE_ADMIN_EMAIL
ENV POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}

ARG POCKETBASE_ADMIN_PASSWORD
ENV POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}

RUN bun run build

# --- Stage 3: minimal runtime image with Node ---
FROM node:22-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Install only ca-certificates for HTTPS outbound calls
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy standalone output generated by Next.js
COPY --from=builder /app/.next/standalone ./

# Ensure static assets and public folder are present in the standalone tree
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]
